"""empty message

Revision ID: 1e48c0fd79d1
Revises: f9c033b8dd2c
Create Date: 2024-05-03 11:08:35.306870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e48c0fd79d1'
down_revision = 'f9c033b8dd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('user_products', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('user_products', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
